 word		type		pre	post			spe

Ariadre		SUBJECT		NONE	SPECIAL|NONE		POSS
Destiny		SUBJECT		NONE	SPECIAL|NONE		POSS
it		SUBJECT		NONE	NONE
she		SUBJECT		NONE	NONE


the		ARTICLE		NONE	NOUN
her		ARTICLE		NONE	NOUN
his		ARTICLE		NONE	NOUN
's		SPECIAL|ARTICLE		SUBJECT|NOSPACE	NOUN	POSS
 ""		ARTICLE		NONE	NOUN

insects		SUBJECT|NOUN	ARTICLE|NONE	NONE	POSS
word		NOUN		ARTICLE	NONE	POSS
number		NOUN		ARTICLE	NONE	POSS


